### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [babanomania/CleanToDO#1]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by babanomania** [comment]
first of all thank you for taking interest in this project, this is basically a personal project of mine in an attempt to learn mobile development. mail me at babanomania@gmail.com
